---
title: "Language detection AI performance for WebIDE"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r echo = T, results = 'hide', warning=F, message=F}

require(data.table)
require(dplyr)
require(reshape2)
require(ggplot2)
require(tidyr)
require(plotly)

models<-c(
"LSTM",
"bibow",
"bigramLSTM",
"tranbowsmallvocab",
"transtd",
"vocabbow",
"vocabbowbatchpkl",
"vocablstm",
"mixedbow4"
)

# I want two plots.
# First plot is a cross comparisons of all models, with maximum likelihood loss and hit percentage
csv_dir_path<-"./csv/"
meltdts<-list()
for (model in models){
  model_path<-paste(model,"_train.csv",sep="")
  csv_path<-paste(csv_dir_path,model_path,sep='')
  dt<-fread(csv_path)
  mbs<-max(dt$batch)
  col<-"all"
  if (model =="mixedbow4"){
    col<-"ml"
  }
  
  to_melt<-data.table(point=dt$epoch*mbs+dt$batch,loss=dt[[col]], hit=dt$hit)
  
  meltdts[[model]]<-to_melt
}


loss_dt<-rbindlist(meltdts,idcol=T)
# loss_dt<-melt(meltdts,id=c("point"), measure.vars=c("loss","hit"))
loss_dt<-loss_dt %>% filter(point<2e06) %>% setDT()
lossplot<-ggplot()+
  geom_smooth(data=loss_dt,span=0.3,se=F,aes(x=point,y=loss,color=.id))+
  labs(y="Training Time Cross Entropy Loss", x="Data point", color="Model")


# styles for plotting
f1 <- list(
  size = 26
)
f2 <- list(
  size = 20
)
a <- list(
  titlefont = f1,
  tickangle = 45,
  tickfont = f2,
  exponentformat ="B",
  dtick=0.25
)
# plots
lossplot <- ggplotly(lossplot, width=1400, height=1000)  %>% layout(legend=list(font=list(size=18)), xaxis=a, yaxis=a)
lossplot

loss_dt<-loss_dt %>% filter(point<2e06) %>% setDT()
hitplot<-ggplot()+
  geom_smooth(data=loss_dt,span=0.3,se=F,aes(x=point,y=hit,color=.id))+
  labs(y="Accuracy", x="Data point", color="Model")
hitplot <- ggplotly(hitplot, width=1400, height=1000)  %>% layout(legend=list(font=list(size=18)), xaxis=a, yaxis=a)
hitplot

# Second plot is the winning model, mixed objectives and validations.
model_path<-paste("mixedbow4","_train.csv",sep="")
csv_path<-paste(csv_dir_path,model_path,sep='')
train<-fread(csv_path)
mbs<-max(train$batch)
train<-train %>% mutate(datapoint=mbs*epoch+batch) %>% select(-epoch, -batch) %>% setDT()
train <- melt(train ,  id.vars = 'datapoint', variable.name = 'series')
# valid set
model_path<-paste("mixedbow4","_valid.csv",sep="")
csv_path<-paste(csv_dir_path,model_path,sep='')
valid<-fread(csv_path)
valid<-valid %>% mutate(datapoint=mbs*(epoch)) %>% select(-epoch) %>% setDT()
valid <- melt(valid ,  id.vars = 'datapoint', variable.name = 'series') 

train_valid<-rbindlist(list(train=train,valid=valid),idcol=T)

winplot<-ggplot()+
geom_smooth(data=train_valid,span=0.1,se=F,aes(x=datapoint,y=value,color=series, linetype=.id))+
  labs(x="Data point",y="Cross Entropy or accuracy", color="model",linetype="Training or validation")+
  scale_y_continuous(expand = c(0,0)) 
winplot <- ggplotly(winplot, width=1400, height=1000)

winplot <- winplot %>% layout(legend=list(font=list(size=18)), xaxis=a, yaxis=a)
# 
# f1<-list(size=18)
# axis <- list(
#   titlefont = f1,
#   tickfont = f1,
# )
# scene = list(
#   xaxis = axis,
#   yaxis = axis)
# legend_style<-list(font=list(size=18))
# p<-plot_ly(train_valid, x=~datapoint, y=~value, type="scatter", mode="lines", linetype=~.id, color=~series)%>%
#   layout(legend=legend_style,xaxis=list(font=list(size=30)))
```

## Training time cross entropy loss (maximum likelihood method) for all models

```{r}
lossplot
```
<br><br><br><br><br><br><br>

## Training time accuracy for all models

```{r, echo=FALSE}
hitplot
```
<br><br><br><br><br><br><br>

## Validation and training performance for mixed objective residual model with bag of words from dictionary

```{r, echo=FALSE}
winplot
```
