#!/usr/bin/env bash

compiler=$1
file=$2

if [[ "$compiler" = "c" || "$compiler" = "cpp" ]]; then
  emcc $file -s WASM=1 -o cwasm.js 2> errFile.txt
  #rm cwasm.html

  if [ "$compiler" = "c" ]; then
    gcc -std=c11 $file -o cClang

  else
    g++ -std=c++14 $file -o cCpp
  fi


elif [ "$compiler" = "rust" ]; then
  # needs to be installed manually and add
  # .cargo/bin to $PATH. wasm-gc needs to
  # be installed through cargo:
  # cargo install --git https://github.com/alexcrichton/wasm-gc
  rustc --target wasm32-unknown-unknown $file -o cwasm.wasm 2> errFile.txt
  #wasm-gc cwasm.wasm cwasm.wasm
  rustc $file -o cRust 2>> errFile.txt

else
  echo "That compiler does not exist or is not available" > errFile.txt
fi
